#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=00:15:00
#$ -l h_vmem=11G
#$ -l gpu=1


module purge

module load python
module load cuda
module load java/1.8.0_382-openjdk

mkdir logs/

# Set up Python environment
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install --upgrade pip

python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
python3 -m pip install tqdm
python3 -m pip install matplotlib
